### ISSUE TITLE
Compatibility with most@^1.0.0

### ISSUE THREAD

**Issue by RamIdeas** [mostjs-community/most-test#3]
The package.json lists the most version as `*` but I hit errors using most version `1.0.4`.

The error is `TypeError: Cannot read property 'XXX' of undefined` where XXX is any of `add`, `empty` or `periodic`.

Your Travis setup is running into the same issues.

It looks like the `Scheduler` constructor now takes a `timeline` as a 2nd argument

From most's own [test helper](https://github.com/cujojs/most/blob/7d27cd50afa2cacb6ee39fc62b424c73d61fe9e5/test/helper/testEnv.js#L34), it looks like you can just pass in a new instance.

**Comment by axefrog** [comment]
Ah dang, yeah. Pull Request? :D

**Comment by axefrog** [comment]
Merged and published, thanks again. https://www.npmjs.com/package/most-test
