### ISSUE TITLE
Bug when used with most-subject and observing before calling run()

### ISSUE THREAD

**Issue by RamIdeas** [mostjs-community/most-test#5]
It's taken me more than 2 days of excruciating debugging to find why my tests are failing but I've finally reduced it down to a simple test which uncovers what I believe to be a bug in most-test. 

This is the test. It will pass in its current form. Uncomment the 2nd line and it will fail.

``` js
import { subject } from 'most-subject'
import { run } from 'most-test'

it( 'exposes most-test bug', async () => {
    const stream = subject();
    // stream.observe( console.log ); // uncommenting this line will make the test fail
    const env = run( stream );
    // stream.observe( console.log ); // uncommenting this line will make no difference
    stream.next(1);
    const { events } = await env.tick();
    expect( events.length ).toBeGreaterThanOrEqual( 1 );
});
```

Changing the 1st line to `const stream = most.just(...)` will also make this test pass no matter whether you uncomment the 2nd line or not.

So, the edge case of:
1. using a `Subject` from most-subject, **and**
2. observing it before passing it to `run()`, behaves unexpectedly.

A quick justification for the 2 prerequisites of this edge case:
1. My events come asynchronously from WebSockets and this is my way of mocking that behaviour.
   - I also have circular dependencies in my streams which cannot be (at least I think) modelled without proxying via a subject
2. The stream I am testing is an intermediate value. It is used to derive another stream. Calling observe on that stream has the same effect.

**Comment by TylorS** [comment]
This could be an issue with the fact that most-subject emits values synchronously, which is not the behavior of the rest of most.js (to be fixed in a later version of most-subject). @axefrog Let me know if this is the case.

**Comment by axefrog** [comment]
@TylorS I don't know if that's the problem. It may be, but I think the problem here is deeper than that.

@RamIdeas Your approach makes me uneasy- calling `stream.observe()` is going to invoke the default scheduler. If it stays alive while calling `run(stream)`, and you have any shared sources (e.g. multicast) in your stream graph, then you're going to have multiple observers operating on the same source instances but with timers that operate under entirely different sets of assumptions. I shudder to think what kinds of side effects and race conditions could occur. The fact that one of your cases fails and the other doesn't could just be luck. Why are you trying to intermix the way you observe streams in your tests?

Take a look at what `run()` is doing [here](https://github.com/mostjs-community/most-test/blob/master/src/run/index.js#L113-L126) in most-test.

Now look at what `observe()` does [here](https://github.com/cujojs/most/blob/master/src/combinator/observe.js#L16-L28),  and [here](https://github.com/cujojs/most/blob/master/src/runSource.js#L19-L22) in most core.

I think your problems will go away if you can ensure that all of your code runs using the same scheduler, which means only using `run()` to observe your streams while testing.

**Comment by RamIdeas** [comment]
_Apologies, this got quite lengthy. The first half was me explaining my set-up. Then I got another idea of what could be causing my issues so I experimented with some tests._

---

Ah ok, I think I understand that the problem is I am causing different schedulers to be used. (Aside: Is the first scheduler swallowing the events because most-subject is automatically `multicast()`?)

To answer your question, I am not intermixing the way I observe streams _in_ my tests. In fact, I don't define the streams in my tests either. They are defined in another file and they are specifically what I am testing. Something like:

In `logic.ts`:

``` js
import input$ from '...'
export const stream1$ = input$.thru(...);
export const stream2$ = stream1$.thru(...);
```

In `logic.test.ts`:

``` js
import { stream1$, stream2$ } from './logic'
it( 'tests stream1$', () => {
    const env = run( stream1$ );
    env.tick()...
});
it( 'tests stream2$', () => {
    const env = run( stream2$ );
    env.tick()...
});
```

Based on what you've said and then me writing out that simplistic overview of my code, I think my tests are conflicting with each other -- the different schedulers are provided by `run()`.

---

I was experiencing two kinds of failing test:
1. Was receiving 0 events from `env.tick()` when I was expecting some
2. Was receiving events but the timestamps were all fixed when I was expecting them to be spaced out over (virtual) time

I've come up with a way to reproduce what I'm seeing:

``` js
import * as most from 'most'
import { subject } from 'most-subject'
import { run } from 'most-test'

const _ = undefined; // dummy value
const input$ = subject();
const stream$ = input$.map( () => most.from( Array(5) ).concatMap( () => most.just(_).delay(1) ) )
                      .switch()
                      .timestamp()
                      .map( pair => pair.time );

it( 'tests stream$', async () => {
    const env = run( stream$ );
    input$.next(_);
    const { events } = await env.tick(5);
    expect( events ).toEqual([ 1, 2, 3, 4, 5 ]);
});

it( 'tests stream$ again', async () => {
    const env = run( stream$ );
    input$.next(_);
    const { events } = await env.tick(5);
    expect( events ).toEqual([ 1, 2, 3, 4, 5 ]); // fails with [ 5, 5, 5, 5, 5 ]
});
```

Both these tests are identical. Run indiviually, they _both_ pass (_obviously_). Run together, the 2nd fails.

My tests weren't identical so made this non-obvious.

**Comment by RamIdeas** [comment]
As I saw it, my options to get this scenario working were either of:
1. recreate my streams beforeEach test -- this meant abstracting my logic into a factory
2. refactor your `run(stream)` method to `run(stream, timer = new VirtualTimer())` and set `env._timer._now = 0` afterEach test -- this works but feels extremely hacky, not to mention unnecessarily verbose at every `run` call: `env = run(stream, env._timer)`
3. rewrite the API of this lib to allow instantiation of a TestEnvironment without a stream and call a `collect(stream)` method after `tick(time)` to get a `Result` -- this would allow testing more than one stream like most's internal `testEnv`

Would you consider a pull request for the last option?

I could even keep the current API intact by having `run` return a `BasicTestEnvironment` which proxies to my new `TestEnvironment` but has the same API as the current `TestEnv`.

I have the API written out in a typescript definition file, if you'd like to see it. I will fill out the implementation tomorrow morning -- these 3am nights are killing me 😅

**Comment by axefrog** [comment]
A pull request would be most welcome, and if you can make it a non-breaking change, as you described above, that would be ideal, thanks!

**Comment by axefrog** [comment]
I think I can close this one.
